{% set name = "gmhi" %}
{% set version = "1.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  host:
    - pip
    - python=3.7
  run:
    - python=3.7
    - bbmap
    - fastqc
    - bowtie2
    - samtools
    - bedtools
    - trimmomatic
    - metaphlan2=2.96.1
    - scikit-learn
    - pandas

test:
  imports:
    - GMHI

about:
  home: https://github.com/danielchang2002/GMHI
  license: MIT
  license_family: MIT
  summary: Gut microbiome health index

