{% set name = "gmhi" %}
{% set version = "1.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  host:
    - pip
    - python=3.7
  run:
    - python=3.7
    - bbmap=38.93
    - fastqc=0.11.9
    - bowtie2=2.4.4
    - samtools=0.1.19
    - bedtools=2.30.0
    - trimmomatic=0.39
    - metaphlan2=2.96.1
    - scikit-learn=1.0.1
    - pandas=1.1.3

test:
  imports:
    - GMHI

about:
  home: https://github.com/danielchang2002/GMHI
  license: MIT
  license_family: MIT
  summary: Gut microbiome health index

