{% set name = "test_gmhi2" %}
{% set version = "1.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  host:
    - pip
    - python=3.7
  run:
    - python=3.7
    - bbmap=38.90
    - fastqc=0.11.8
    - bowtie2=2.4.4
    - samtools=1.9
    - bedtools=2.27.1
    - trimmomatic=0.39
    - metaphlan=3.0.13

test:
  imports:
    - GMHI2

about:
  home: https://github.com/danielchang2002/GMHI2
  license: MIT
  license_family: MIT
  summary: Gut microbiome health index 2

